version: 2.1
executors:
  node:
    docker:
      - image: node:10
    working_directory: ~/reason-date-fns

jobs:
  test:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
      - run:
          name: Check that nothing crashes
          command: yarn demo:test

  release:
    executor: node
    steps:
      - attach_workspace:
          at: ~/reason-date-fns
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/reason-date-fns/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
